---
# secure ssh
- name: configure ssh to only allow in the maintenance user
  template:
    src=../templates/sshd.config.j2
    dest=/etc/ssh/sshd_config
    owner=root
    mode=0644
  notify:
    - reload sshd
